CREATE DATABASE reactstore;


CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email text,
    password text
);

CREATE TABLE IF NOT EXISTS products(   
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text,
    price text,
    sex text,
    stock text,
    categories text,
    userid integer REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS productimages (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name text,
        path text,
        productsid integer REFERENCES products(id)
);